#!/bin/bash --login
#
# Starts the entire application including the webserver and job workers.
#

source $HOME/bin/env.sh

# Clean up any stale pid files, otherwise DJ won't start.
( ~/bin/stop-delayed-job )

( ~/bin/start-passenger )
( ~/bin/start-delayed-job )

exit 0
