#!/bin/bash --login

source $HOME/bin/env.sh

# Stop Passenger
( cd $DLS_HOME ; bundle exec passenger stop -p 3000 )

# Stop Delayed Job
( ~/bin/delayed_job stop default 1 )
( ~/bin/delayed_job stop download 1 )
( ~/bin/delayed_job stop download 2 )

exit 0
