#!/bin/bash
###
### boot - service hook for booting up services; called by
### /etc/init.d/services_startup
###

# Load environment variables
HOME=/home/dls
. $HOME/.bashrc

# (In case it didn't shut down cleanly)
rm -f $HOME/kumquat/tmp/pids/server.pid

$HOME/bin/start-rails
