#!/bin/bash
###
### shutdown - service hook for shutting down services; called by
### /etc/init.d/services_startup
###

# Load environment variables
HOME=/home/dls
. $HOME/.bashrc

$HOME/bin/stop-rails
